version: "3.9"

networks:
  backend-db:
    driver: bridge
volumes:
  db_data:
    name: db_data

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: luca1593
      MYSQL_DATABASE: grst
      MYSQL_USER: luca
      MYSQL_PASSWORD: luca1593
    ports:
      - "3302:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-db

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin5.2
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8083:80"
    networks:
      - backend-db
  grstapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grstapp
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/grst?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: luca
      SPRING_DATASOURCE_PASSWORD: luca1593
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    ports:
      - "8084:8080"
    networks:
      - backend-db