spring:
  application:
    name: gsrt
  datasource:
    url: jdbc:mysql://12.24.5.100:3306/grst?createDatabaseIfNotExist=true
    username: luca
    password: LucA$1593
    driver-class-name: com.mysql.cj.jdbc.Driver
    main:
      allow-circular-references: true
  jpa:
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  error:
    whitelabel:
      enabled: false
  port: 8081