version: "3.9"

networks:
  backend-db:
    driver: bridge

services:
  db:
    image: mysql:lts
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: luca1593
      MYSQL_DATABASE: grst
      MYSQL_USER: luca
      MYSQL_PASSWORD: luca1593
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-db

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-5.2
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - backend-db

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    restart: always
    ports:
      - "143:143"
      - "2525:25"
      - "5000:80"
    networks:
      - backend-db

volumes:
  db_data:

